project:
  type: website

website:
  title: "Bowen Qin"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/FangyaunLi
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: quarze
      dark: darkly
    css: styles.css

comments: 
  giscus: 
    repo: FangyaunLi/My-Blog


